# Generated by Django 4.2.4 on 2024-03-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='legalauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=16)),
                ('dept', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pinc', models.IntegerField()),
            ],
        ),
    ]
