# Generated by Django 4.2.4 on 2024-04-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
