# Generated by Django 4.2.4 on 2024-04-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_news_source_alter_news_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='Media/'),
        ),
        migrations.AddField(
            model_name='news',
            name='img2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Media/'),
        ),
        migrations.AddField(
            model_name='news',
            name='img3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Media/'),
        ),
        migrations.AddField(
            model_name='news',
            name='img4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Media/'),
        ),
        migrations.AddField(
            model_name='news',
            name='img5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Media/'),
        ),
    ]
