# Generated by Django 4.2.4 on 2024-02-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportcrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcfname', models.CharField(max_length=50)),
                ('rcphone', models.IntegerField()),
                ('rcdob', models.DateField()),
                ('rcemail', models.EmailField(max_length=254)),
                ('rcgender', models.CharField(max_length=50)),
                ('rcid', models.ImageField(upload_to='')),
                ('rccategory', models.CharField(max_length=50)),
                ('rcsocial', models.CharField(max_length=50)),
                ('rcincidate', models.DateField()),
                ('rcincitime', models.TimeField()),
                ('rconetime', models.CharField(max_length=10)),
                ('rclostmoney', models.CharField(max_length=10)),
                ('rcstreet', models.CharField(max_length=30)),
                ('rcarea', models.CharField(max_length=20)),
                ('rccity', models.CharField(max_length=20)),
                ('rcstate', models.CharField(max_length=20)),
                ('rcdetail', models.CharField(max_length=500)),
                ('rcweapon', models.CharField(max_length=10)),
                ('rcidentity', models.CharField(max_length=10)),
                ('rcdesc', models.CharField(max_length=500)),
                ('rcbank', models.CharField(max_length=50)),
                ('rcproof', models.ImageField(upload_to='')),
                ('rcextra', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
