# Generated by Django 4.2.4 on 2024-02-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_reportcrime_rcid_remove_reportcrime_rcproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcrime',
            name='rcgender',
            field=models.CharField(max_length=10),
        ),
    ]
