# Generated by Django 4.2.4 on 2024-02-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_reportcrime_rcgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcrime',
            name='rcid',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Media/'),
        ),
        migrations.AddField(
            model_name='reportcrime',
            name='rcproof',
            field=models.FileField(blank=True, default='', null=True, upload_to='Media/'),
        ),
        migrations.AlterField(
            model_name='reportcrime',
            name='rcbank',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reportcrime',
            name='rcdesc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='reportcrime',
            name='rcextra',
            field=models.CharField(default='', max_length=500),
        ),
    ]
