# Generated by Django 4.2.4 on 2024-02-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_reportcrime_rcid_reportcrime_rcproof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcrime',
            name='rcid',
            field=models.FileField(blank=True, default='', null=True, upload_to='Media/'),
        ),
    ]
