# Generated by Django 4.2.4 on 2024-02-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_reportcrime_rcid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcrime',
            name='rcid',
            field=models.FileField(blank=True, default='', null=True, upload_to='images'),
        ),
    ]
