# Generated by Django 4.2.4 on 2024-02-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcrime',
            name='rcspecify',
            field=models.CharField(default='', max_length=50),
        ),
    ]
