# Generated by Django 4.2.4 on 2024-03-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_reportcrime_rcspecify'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcrime',
            name='rcarea1',
            field=models.CharField(default='', max_length=20),
        ),
    ]
