# Generated by Django 4.2.4 on 2024-04-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_reportcrime_rcarea1'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcrime',
            name='rcdept',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reportcrime',
            name='rcstatus',
            field=models.CharField(default='', max_length=200),
        ),
    ]
